# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
	${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "intel-bsp"
BBFILE_PATTERN_intel-bsp := "^${LAYERDIR}/"
BBFILE_PRIORITY_intel-bsp = "9"

LAYERSERIES_COMPAT_intel-bsp = "scarthgap"
LAYERDEPENDS_intel-bsp = "intel"

# Skip parsing recipes with private sources if not used in build
BBMASK:append = " ${@bb.utils.contains('PREFERRED_PROVIDER_virtual/kernel', 'linux-intel-private', '', \
                  'meta-intel-bsp/recipes-kernel/linux-intel-private', d)} \
		"
